using GHIElectronics.TinyCLR.Devices.Display;
using GHIElectronics.TinyCLR.Devices.Gpio;
using GHIElectronics.TinyCLR.Devices.I2c;
//using GHIElectronics.TinyCLR.DUE;
//using GHIElectronics.TinyCLR.Native;
using GHIElectronics.TinyCLR.Pins;
using GHIElectronics.TinyCLR.UI;
using GHIElectronics.TinyCLR.UI.Controls;
using GHIElectronics.TinyCLR.UI.Media;
using System.Diagnostics;
using System.Drawing;
using System.Threading;
using GHIElectronics.TinyCLR.Drivers.FocalTech.FT5xx6;
using TestApp.Properties;
using System;
using ZXing;
using GHIElectronics.TinyCLR.UI.Media.Imaging;
using System.IO;

namespace TestApp
{
    class Program : Application
    {
        public Program(DisplayController d) : base(d)
        {
        }
        static Program app;
        static Graphics Screen;
        static Bitmap ScreenBmp;

        static Text txtTitle;
        static Timer timer;
        static DataGrid GvData;
        static Font font;
        static GHIElectronics.TinyCLR.UI.Controls.Image qrImage;
        static GHIElectronics.TinyCLR.UI.Window mainWindow;
        static void Main()
        {
            GpioPin backlight = GpioController.GetDefault().OpenPin(SC20260.GpioPin.PA15);
            backlight.SetDriveMode(GpioPinDriveMode.Output);
            backlight.Write(GpioPinValue.High);
            var display = DisplayController.GetDefault();

            var controllerSetting = new
                GHIElectronics.TinyCLR.Devices.Display.ParallelDisplayControllerSettings
            {
                Width = 800,
                Height = 480,
                DataFormat = DisplayDataFormat.Rgb565,
                Orientation = DisplayOrientation.Degrees0, //Rotate Display.
                PixelClockRate = 24000000,
                PixelPolarity = false,
                DataEnablePolarity = false,
                DataEnableIsFixed = false,
                HorizontalFrontPorch = 16,
                HorizontalBackPorch = 46,
                HorizontalSyncPulseWidth = 1,
                HorizontalSyncPolarity = false,
                VerticalFrontPorch = 7,
                VerticalBackPorch = 23,
                VerticalSyncPulseWidth = 1,
                VerticalSyncPolarity = false,
            };

            display.SetConfiguration(controllerSetting);
            display.Enable();

            var screen = Graphics.FromHdc(display.Hdc);
            var i2cController = I2cController.FromName(SC20100.I2cBus.I2c1);
            var gpioController = GpioController.GetDefault();

            var touch = new FT5xx6Controller(i2cController.GetDevice(FT5xx6Controller.GetConnectionSettings()),gpioController.OpenPin(SC20260.GpioPin.PJ14));
            touch.Orientation = FT5xx6Controller.TouchOrientation.Degrees0; //Rotate touch coordinates.

            font = Resources.GetFont(Resources.FontResources.NinaB);
            GHIElectronics.TinyCLR.UI.OnScreenKeyboard.Font = font;
            app = new Program(display);
            touch.TouchMove += (_, e) => {
                app.InputProvider.RaiseTouch(e.X, e.Y, GHIElectronics.TinyCLR.UI.Input.TouchMessages.Move, System.DateTime.UtcNow);
            };
            touch.TouchUp += (_, e) => {
                app.InputProvider.RaiseTouch(e.X, e.Y, GHIElectronics.TinyCLR.UI.Input.TouchMessages.Up, System.DateTime.UtcNow);
            };
            touch.TouchDown += (_, e) => {
                app.InputProvider.RaiseTouch(e.X, e.Y, GHIElectronics.TinyCLR.UI.Input.TouchMessages.Down, System.DateTime.UtcNow);
            };

            //init qr
            ScreenBmp =new Bitmap(120, 120);
            Screen = Graphics.FromImage(ScreenBmp);
            mainWindow = Program.CreateWindow(display);
            app.Run(mainWindow);
            
        }

        #region QRCode
        static void EncodeQR(string Content)
        {
            txtTitle.TextContent = "Generating barcode...";
            txtTitle.Invalidate();

            var ft = Resources.GetFont(Resources.FontResources.small);
            DateTime dt = DateTime.Now;
            var writer = new ZXing.QrCode.QRCodeWriter();

            var matrix = writer.encode(Content, BarcodeFormat.QR_CODE, 120, 120);
            var bitmap = matrix.ToBitmap(BarcodeFormat.QR_CODE, null);

            var whiteBrush = new SolidBrush(System.Drawing.Color.White);
            var blackBrush = new SolidBrush(System.Drawing.Color.Black);
            var pen = new System.Drawing.Pen(System.Drawing.Color.Black,1);
            Screen.FillRectangle(whiteBrush, 0, 0, Screen.Width, Screen.Height);
            Screen.DrawRectangle(pen, 0, 0, Screen.Width, Screen.Height);
            Screen.DrawImage(2, 2, bitmap, 0, 0, 119, 119, 255);
            //Screen.DrawString(Content, ft, blackBrush, 2, 130);
            Screen.Flush();

            txtTitle.TextContent = "QR: "+Content;
            txtTitle.Invalidate();
            Debug.WriteLine("QR Encoded");
        }
        private void DecodeQR()
        {
            txtTitle.TextContent = "This will take a while...";
            var memory = new MemoryStream(Convert.FromBase64String(bitmapString));
            var bmp = Bitmap.FromStream(memory);
            var imgSrc = BitmapImage.FromGraphics(Screen);
            qrImage.Source = imgSrc;

            var operation = mainWindow.Dispatcher.BeginInvoke((obj) =>
            {
                var reader = new ZXing.BarcodeReader { TryHarder = false };
                return reader.Decode((Bitmap)obj);
            }, bmp);
            operation.Wait();
            if (operation.Result != null)
            {
                txtTitle.TextContent = ((ZXing.Result)(operation.Result)).Text;
            }
            else
            {
                txtTitle.TextContent = "No barcode found.";
            }
        }

        private const string bitmapString =
           "Qk0yJAAAAAAAADYEAAAoAAAAWQAAAFkAAAABAAgAAAAAAPwfAAAAAAAAAAAAAAABAAAAAAAABAIEAPz+/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQAAAAEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAQEBAAAAAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQEBAQEAAAABAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQAAAAEBAQAAAAAAAAEBAQAAAAAAAAEBAQAAAAEBAQEBAQEBAQAAAAAAAAAAAAEBAQAAAAAAAAAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAAAAAQEBAAAAAAAAAQEBAAAAAAAAAQEBAAAAAQEBAQEBAQEBAAAAAAAAAAAAAQEBAAAAAAAAAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEAAAABAQEAAAAAAAABAQEAAAAAAAABAQEAAAABAQEBAQEBAQEAAAAAAAAAAAABAQEAAAAAAAAAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQAAAAAAAAAAAAEBAQAAAAEBAQEBAQEBAQAAAAAAAAAAAAEBAQEBAQEBAQAAAAAAAAEBAQAAAAAAAAEBAQAAAAAAAAAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAAAAAAAAAAAAAQEBAAAAAQEBAQEBAQEBAAAAAAAAAAAAAQEBAQEBAQEBAAAAAAAAAQEBAAAAAAAAAQEBAAAAAAAAAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEAAAAAAAAAAAABAQEAAAABAQEBAQEBAQEAAAAAAAAAAAABAQEBAQEBAQEAAAAAAAABAQEAAAAAAAABAQEAAAAAAAAAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQAAAAAAAAAAAAEBAQAAAAEBAQAAAAEBAQEBAQAAAAAAAAEBAQAAAAEBAQEBAQAAAAAAAAAAAAEBAQAAAAEBAQAAAAAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAAAAAAAAAAAAAQEBAAAAAQEBAAAAAQEBAQEBAAAAAAAAAQEBAAAAAQEBAQEBAAAAAAAAAAAAAQEBAAAAAQEBAAAAAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEAAAAAAAAAAAABAQEAAAABAQEAAAABAQEBAQEAAAAAAAABAQEAAAABAQEBAQEAAAAAAAAAAAABAQEAAAABAQEAAAAAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQAAAAAAAAAAAAEBAQAAAAEBAQAAAAAAAAAAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAEBAQEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAAAAAAAAAAAAAQEBAAAAAQEBAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAQEBAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEAAAAAAAAAAAABAQEAAAABAQEAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAABAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQAAAAAAAAEBAQAAAAAAAAAAAAAAAAEBAQEBAQEBAQAAAAEBAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAAAAAAAAAQEBAAAAAAAAAAAAAAAAAQEBAQEBAQEBAAAAAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQEAAAAAAAABAQEAAAAAAAAAAAAAAAABAQEBAQEBAQEAAAABAQEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQAAAAEBAQAAAAAAAAAAAAEBAQEBAQAAAAEBAQAAAAEBAQAAAAAAAAEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAAAAAQEBAAAAAAAAAAAAAQEBAQEBAAAAAQEBAAAAAQEBAAAAAAAAAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEAAAABAQEAAAAAAAAAAAABAQEBAQEAAAABAQEAAAABAQEAAAAAAAABAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAEBAQEBAQAAAAEBAQEBAQAAAAEBAQEBAQEBAQAAAAEBAQEBAQAAAAEBAQEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAQEBAQEBAAAAAQEBAQEBAAAAAQEBAQEBAQEBAAAAAQEBAQEBAAAAAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAABAQEBAQEAAAABAQEBAQEAAAABAQEBAQEBAQEAAAABAQEBAQEAAAABAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQAAAAEBAQAAAAEBAQAAAAEBAQAAAAEBAQAAAAAAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAAAAAEBAQEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAAAAAQEBAAAAAQEBAAAAAQEBAAAAAQEBAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAQEBAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEAAAABAQEAAAABAQEAAAABAQEAAAABAQEAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAABAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQAAAAEBAQAAAAAAAAEBAQAAAAEBAQAAAAEBAQAAAAAAAAEBAQAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAAAAAQEBAAAAAAAAAQEBAAAAAQEBAAAAAQEBAAAAAAAAAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEAAAABAQEAAAAAAAABAQEAAAABAQEAAAABAQEAAAAAAAABAQEAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAAAAAEBAQEBAQEBAQEBAQAAAAEBAQAAAAEBAQEBAQEBAQEBAQAAAAEBAQAAAAEBAQAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAAAAAQEBAQEBAQEBAQEBAAAAAQEBAAAAAQEBAQEBAQEBAQEBAAAAAQEBAAAAAQEBAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAAAAAABAQEBAQEBAQEBAQEAAAABAQEAAAABAQEBAQEBAQEBAQEAAAABAQEAAAABAQEAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQAAAAAAAAAAAAAAAAEBAQAAAAAAAAEBAQAAAAAAAAEBAQAAAAEBAQAAAAAAAAEBAQEBAQEBAQAAAAEBAQEBAQAAAAEBAQEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAAAAAAAAAAAAAAAAAQEBAAAAAAAAAQEBAAAAAAAAAQEBAAAAAQEBAAAAAAAAAQEBAQEBAQEBAAAAAQEBAQEBAAAAAQEBAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEAAAAAAAAAAAAAAAABAQEAAAAAAAABAQEAAAAAAAABAQEAAAABAQEAAAAAAAABAQEBAQEBAQEAAAABAQEBAQEAAAABAQEBAQEBAQEBAAAAAQEBAQEBAQEBAQAAAAEBAQAAAAEBAQEBAQAAAAAAAAAAAAAAAAAAAAEBAQAAAAEBAQEBAQAAAAEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAQEBAAAAAQEBAAAAAQEBAQEBAAAAAAAAAAAAAAAAAAAAAQEBAAAAAQEBAQEBAAAAAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEBAQEAAAABAQEAAAABAQEBAQEAAAAAAAAAAAAAAAAAAAABAQEAAAABAQEBAQEAAAABAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQAAAAAAAAEBAQAAAAEBAQAAAAEBAQEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQAAAAEBAQAAAAAAAAAAAAAAAAAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAAAAAAAAAQEBAAAAAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAAAAAQEBAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEAAAAAAAABAQEAAAABAQEAAAABAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQEAAAABAQEAAAAAAAAAAAAAAAAAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAAAAAEBAQEBAQAAAAAAAAAAAAAAAAEBAQAAAAEBAQAAAAEBAQEBAQEBAQAAAAEBAQAAAAEBAQEBAQAAAAAAAAEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAAAAAQEBAQEBAAAAAAAAAAAAAAAAAQEBAAAAAQEBAAAAAQEBAQEBAQEBAAAAAQEBAAAAAQEBAQEBAAAAAAAAAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAAAAAABAQEBAQEAAAAAAAAAAAAAAAABAQEAAAABAQEAAAABAQEBAQEBAQEAAAABAQEAAAABAQEBAQEAAAAAAAABAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQEBAQAAAAEBAQAAAAEBAQAAAAEBAQAAAAEBAQEBAQAAAAAAAAEBAQEBAQAAAAAAAAAAAAEBAQEBAQAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEAAAABAQEBAQEBAQEBAAAAAQEBAAAAAQEBAAAAAQEBAAAAAQEBAQEBAAAAAAAAAQEBAQEBAAAAAAAAAAAAAQEBAQEBAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQEAAAABAQEAAAABAQEAAAABAQEAAAABAQEBAQEAAAAAAAABAQEBAQEAAAAAAAAAAAABAQEBAQEAAAAAAAAAAAAAAAAAAAABAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAAAAAEBAQAAAAAAAAEBAQAAAAEBAQEBAQAAAAEBAQAAAAAAAAEBAQAAAAEBAQAAAAEBAQAAAAEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAAAAAQEBAAAAAAAAAQEBAAAAAQEBAQEBAAAAAQEBAAAAAAAAAQEBAAAAAQEBAAAAAQEBAAAAAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAAAAAABAQEAAAAAAAABAQEAAAABAQEBAQEAAAABAQEAAAAAAAABAQEAAAABAQEAAAABAQEAAAABAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAEBAQEBAQEBAQAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAAQEBAQEBAQEBAAAAAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAABAQEBAQEBAQEAAAAAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAEBAQAAAAEBAQAAAAEBAQAAAAEBAQAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAQEBAAAAAQEBAAAAAQEBAAAAAQEBAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAABAQEAAAABAQEAAAABAQEAAAABAQEAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQAAAAEBAQAAAAEBAQEBAQAAAAEBAQAAAAEBAQAAAAEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAAAAAQEBAAAAAQEBAQEBAAAAAQEBAAAAAQEBAAAAAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEAAAABAQEAAAABAQEBAQEAAAABAQEAAAABAQEAAAABAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQAAAAAAAAAAAAEBAQAAAAEBAQEBAQEBAQAAAAAAAAAAAAEBAQAAAAEBAQAAAAEBAQAAAAEBAQAAAAAAAAAAAAEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAAAAAAAAAAAAAQEBAAAAAQEBAQEBAQEBAAAAAAAAAAAAAQEBAAAAAQEBAAAAAQEBAAAAAQEBAAAAAAAAAAAAAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEAAAAAAAAAAAABAQEAAAABAQEBAQEBAQEAAAAAAAAAAAABAQEAAAABAQEAAAABAQEAAAABAQEAAAAAAAAAAAABAQEAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQAAAAAAAAAAAAEBAQAAAAEBAQEBAQEBAQAAAAAAAAAAAAAAAAEBAQEBAQAAAAEBAQAAAAEBAQAAAAAAAAAAAAEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAAAAAAAAAAAAAQEBAAAAAQEBAQEBAQEBAAAAAAAAAAAAAAAAAQEBAQEBAAAAAQEBAAAAAQEBAAAAAAAAAAAAAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEAAAAAAAAAAAABAQEAAAABAQEBAQEBAQEAAAAAAAAAAAAAAAABAQEBAQEAAAABAQEAAAABAQEAAAAAAAAAAAABAQEAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQAAAAAAAAAAAAEBAQAAAAEBAQEBAQAAAAEBAQAAAAEBAQAAAAAAAAEBAQAAAAEBAQAAAAEBAQAAAAAAAAAAAAEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAAAAAAAAAAAAAQEBAAAAAQEBAQEBAAAAAQEBAAAAAQEBAAAAAAAAAQEBAAAAAQEBAAAAAQEBAAAAAAAAAAAAAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEAAAAAAAAAAAABAQEAAAABAQEBAQEAAAABAQEAAAABAQEAAAAAAAABAQEAAAABAQEAAAABAQEAAAAAAAAAAAABAQEAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQAAAAAAAAEBAQEBAQEBAQAAAAEBAQAAAAEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAQEBAAAAAAAAAQEBAQEBAQEBAAAAAQEBAAAAAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQEBAQEAAAAAAAABAQEBAQEBAQEAAAABAQEAAAABAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAAAAAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAEBAQEBAQAAAAEBAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEAAAABAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAQEBAQEBAAAAAQEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAABAQEBAQEAAAABAQEBAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAA=";
    
    #endregion

    private static UIElement Elements2()
        {
            var panel = new StackPanel(Orientation.Vertical);

            var txt1 = new TextBox()
            {
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Top,
                Width = 300,
                Mode = TextBox.TextMode.Password
            };

            txt1.Font = font;
            txt1.SetMargin(5);
            txt1.Text = "This text will be masked.";

            txtTitle = new Text(font, "The text above using mode = password")
            {
                ForeColor = Colors.White,
                HorizontalAlignment = HorizontalAlignment.Center,
            };

            txtTitle.SetMargin(5);

            var progress1 = new ProgressBar()
            {
                Width = 400,
                Height = 25,
                HorizontalAlignment = HorizontalAlignment.Center,
            };
            var slider1 = new Slider(400, 50);
            slider1.SetMargin(5);
            //slider1.Height = 100;
            slider1.ValueChangedEvent += (object sender, ValueChangedEventArgs args) =>
            {
                progress1.Value = (int)args.SliderValue;
                Debug.WriteLine("val:" + args.SliderValue);
                progress1.Invalidate();
            };
            GvData = new DataGrid(500, 200, 30, 5);

            GvData.AddColumn(new DataGridColumn("Time", 100));
            GvData.AddColumn(new DataGridColumn("Sensor A", 100));
            GvData.AddColumn(new DataGridColumn("Sensor B", 100));
            GvData.AddColumn(new DataGridColumn("QRData", 180));

           

            qrImage = new GHIElectronics.TinyCLR.UI.Controls.Image() { HorizontalAlignment= HorizontalAlignment.Center, VerticalAlignment= VerticalAlignment.Center, Width=300,Height=300 };
           
            qrImage.SetMargin(10);

            panel.Children.Add(txt1);
            panel.Children.Add(txtTitle);
            panel.Children.Add(progress1);
            panel.Children.Add(slider1);
            panel.Children.Add(GvData);
            panel.Children.Add(qrImage);

            EncodeQR("Hello World!");
            var imgSrc = BitmapImage.FromGraphics(Screen);
            qrImage.Source = imgSrc;

            GvData.TapCellEvent += (object sender, GHIElectronics.TinyCLR.UI.Glide.TapCellEventArgs args)
            =>
            {
                if (GvData.SelectedIndex >= 0)
                {
                    var data = GvData.GetCellData(3, GvData.SelectedIndex).ToString();
                    EncodeQR(data);
                    var imgSrc = BitmapImage.FromGraphics(Screen);
                    qrImage.Source = imgSrc;
                }
            };

            return panel;
        }

      




        /*
        //unused
        private static UIElement Elements3()
        {
            var canvas = new Canvas();
            var border = new Border();

            border.SetBorderThickness(10);
            border.BorderBrush = new SolidColorBrush(Colors.Red);

            Canvas.SetLeft(border, 20);
            Canvas.SetTop(border, 20);

            var txt = new TextBox();
            txt.Mode = TextBox.TextMode.Password;
            txt.Font = font;
            txt.Text = "TinyCLR is Great!";

            border.Child = txt;
            canvas.Children.Add(border);

            return canvas;
        }

        private static UIElement Elements()
        {
            
            var panel = new Panel();

            var txt1 = new TextBox()
            {
                HorizontalAlignment = HorizontalAlignment.Left,
                VerticalAlignment = VerticalAlignment.Top,
            };

            txt1.Font = font;
            txt1.SetMargin(20);
            txt1.Text = "Hello World!";

            var txt2 = new Text(font, "TinyCLR is Great!")
            {
                ForeColor = Colors.White,
                HorizontalAlignment = HorizontalAlignment.Right,
            };

            txt2.SetMargin(20);

            var rect = new GHIElectronics.TinyCLR.UI.Shapes.Rectangle(200, 10)
            {
                Fill = new SolidColorBrush(Colors.Green),
                HorizontalAlignment = HorizontalAlignment.Center,
            };

            var slider1 = new Slider();
            slider1.Width = 300;

            //slider1.SetMargin(20);
            slider1.ValueChangedEvent += (object sender, ValueChangedEventArgs args)=>
            {
                Debug.WriteLine("val:" + args.SliderValue);
            };
            panel.Children.Add(txt1);
            panel.Children.Add(txt2);
            panel.Children.Add(rect);
            panel.Children.Add(slider1);

            return panel;
        }
        */

        private static Window CreateWindow(DisplayController display)
        {
            var window = new Window
            {
                Height = (int)display.ActiveConfiguration.Height,
                Width = (int)display.ActiveConfiguration.Width
            };

            window.Background = new LinearGradientBrush
                (Colors.Blue, Colors.Teal, 0, 0, window.Width, window.Height);
           
            window.Visibility = Visibility.Visible;
            window.Child = Elements2();
            Random rnd = new Random();
            int counter = 0;
            if (GvData != null)
            {
                var links = new string[] { "https://google.com","https://ghielectronics.com","https://bing.com","https://yahoo.com","https://twitter.com" };
                //generate sample data
                for (int i = 0; i < links.Length; i++)
                {
                    //insert to db
                    var item = new DataGridItem(new object[] { DateTime.Now.ToString("HH:mm:ss"), $"{(20 + rnd.Next() * 50).ToString("n2")}C", $"{(rnd.Next() * 1000).ToString("n2")}L", links[i]});
                    //add data to grid
                    GvData.AddItem(item);
                }
                GvData.Invalidate();
                /*
                timer = new Timer((object o) =>
                {
                    Application.Current.Dispatcher.Invoke(TimeSpan.FromMilliseconds(1), _ =>
                    {
                        //insert to db
                        var item = new DataGridItem(new object[] { DateTime.Now.ToString("HH:mm:ss"), $"{(20 + rnd.Next() * 50).ToString("n2")}C", $"{(rnd.Next() * 1000).ToString("n2")}L" });
                        //add data to grid
                        GvData.AddItem(item);
                        GvData.Invalidate();
                        if (counter++ > 4)
                        {
                            counter = 0;
                            GvData.Clear();
                        }
                        return null;
                    }, null);

                }, null, 1000, 1000);*/
            }
            return window;
        }
    }
}
